(make-repeatable-pair 'evil-next-line 'evil-previous-line)
(make-repeatable-pair 'evil-next-visual-line 'evil-previous-visual-line)
(make-repeatable-pair 'forward-char 'backward-char)
(make-repeatable-pair 'forward-word 'backward-word)
(make-repeatable-pair 'forward-sentence 'backward-sentence)

(make-repeatable-pair 'evil-forward-word-begin 'evil-backward-word-begin)
(make-repeatable-pair 'evil-forward-WORD-begin 'evil-backward-WORD-begin)
(make-repeatable-pair 'evil-forward-word-end 'evil-backward-word-end)
(make-repeatable-pair 'evil-forward-WORD-end 'evil-backward-WORD-end)
(make-repeatable-pair 'evil-forward-char 'evil-backward-char)
(make-repeatable-pair 'evil-forward-paragraph 'evil-backward-paragraph)
(make-repeatable-pair 'evil-forward-sentence 'evil-backward-sentence)
(make-repeatable-pair 'evil-forward-section-begin 'evil-backward-section-begin)
(make-repeatable-pair 'evil-forward-section-end 'evil-backward-section-end)
(make-repeatable-pair 'evil-previous-open-paren 'evil-next-open-paren)
(make-repeatable-pair 'evil-previous-close-paren 'evil-next-close-paren)
(make-repeatable-pair 'evil-previous-open-brace 'evil-next-open-brace)
(make-repeatable-pair 'evil-previous-close-brace 'evil-next-close-brace)
(make-repeatable-pair 'evil-jump-forward 'evil-jump-backward)

(fset 'repeatable-evil-find-char (make-repeatable-motion 'evil-find-char 'evil-repeat-find-char 'evil-repeat-find-char-reverse))
(fset 'repeatable-evil-find-char-reverse (make-repeatable-motion 'evil-find-char-reverse 'evil-repeat-find-char-reverse 'evil-repeat-find-char))
(fset 'repeatable-evil-find-char-to (make-repeatable-motion 'evil-find-char-to 'evil-repeat-find-char 'evil-repeat-find-char-reverse))
(fset 'repeatable-evil-find-char-to-backward (make-repeatable-motion 'evil-find-char-to-backward 'evil-repeat-find-char-reverse 'evil-repeat-find-char))
(fset 'repeatable-evil-search-forward (make-repeatable-motion 'evil-search-forward 'evil-search-next 'evil-search-previous))
(fset 'repeatable-evil-search-backward (make-repeatable-motion 'evil-search-backward 'evil-search-previous 'evil-search-next))
(fset 'repeatable-evil-search-word-forward (make-repeatable-motion 'evil-search-word-forward 'evil-search-next 'evil-search-previous))
(fset 'repeatable-evil-search-word-backward (make-repeatable-motion 'evil-search-word-backward 'evil-search-previous 'evil-search-next))
